In [1]:
import seaborn as sns

df = sns.load_dataset('titanic')

print(df.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [3]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [4]:
df['age']=df['age'].fillna(df['age'].mean())

In [5]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [6]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.002015    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   29.699118    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [7]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [8]:
df['deck'] = df['deck'].astype(object)
df['deck'] = df['deck'].fillna('Unknown')

In [9]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
deck           0
embark_town    2
alive          0
alone          0
dtype: int64

In [10]:
df.dropna(inplace=True)

In [11]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [12]:
df['sex']=df['sex'].map({
    'male' : '0',
    'female' : '1'})

In [13]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,S,Third,man,True,Unknown,Southampton,no,False
1,1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,1,26.0,0,0,7.9250,S,Third,woman,False,Unknown,Southampton,yes,True
3,1,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,0,35.0,0,0,8.0500,S,Third,man,True,Unknown,Southampton,no,True

In [14]:
df['who'].value_counts()

who
man      537
woman    269
child     83
Name: count, dtype: int64

In [15]:
df['who']=df['who'].map({
    'man': '1','woman':'0','child':'3'})

In [16]:
df['who'].value_counts()

who
1    537
0    269
3     83
Name: count, dtype: int64

In [17]:
df['adult_male'].value_counts()

adult_male
True     537
False    352
Name: count, dtype: int64

In [18]:
df['adult_male'] = df['adult_male'].astype(int)

In [19]:
import seaborn as sns

df['adult_male'] = sns.load_dataset('titanic')['adult_male']

In [20]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,S,Third,1,True,Unknown,Southampton,no,False
1,1,1,1,38.0,1,0,71.2833,C,First,0,False,C,Cherbourg,yes,False
2,1,3,1,26.0,0,0,7.9250,S,Third,0,False,Unknown,Southampton,yes,True
3,1,1,1,35.0,1,0,53.1000,S,First,0,False,C,Southampton,yes,False
4,0,3,0,35.0,0,0,8.0500,S,Third,1,True,Unknown,Southampton,no,True

In [21]:
df['adult_male'] = df['adult_male'].map({
    True: 1,
    False: 0
})

In [22]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,S,Third,1,1,Unknown,Southampton,no,False
1,1,1,1,38.0,1,0,71.2833,C,First,0,0,C,Cherbourg,yes,False
2,1,3,1,26.0,0,0,7.9250,S,Third,0,0,Unknown,Southampton,yes,True
3,1,1,1,35.0,1,0,53.1000,S,First,0,0,C,Southampton,yes,False
4,0,3,0,35.0,0,0,8.0500,S,Third,1,1,Unknown,Southampton,no,True

In [23]:
df['class'].value_counts()

class
Third     491
First     214
Second    184
Name: count, dtype: int64

In [24]:
df['class']=df['class'].map({'First' : '1', 'Second' : '2', 'Third': '3'})

In [25]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,S,3,1,1,Unknown,Southampton,no,False
1,1,1,1,38.0,1,0,71.2833,C,1,0,0,C,Cherbourg,yes,False
2,1,3,1,26.0,0,0,7.9250,S,3,0,0,Unknown,Southampton,yes,True
3,1,1,1,35.0,1,0,53.1000,S,1,0,0,C,Southampton,yes,False
4,0,3,0,35.0,0,0,8.0500,S,3,1,1,Unknown,Southampton,no,True

In [26]:
df['alive'].value_counts()

alive
no     549
yes    340
Name: count, dtype: int64

In [27]:
df['alive']=df['alive'].map({'yes':'1', 'no' : '0'})

In [28]:
df['alive'].value_counts()

alive
0    549
1    340
Name: count, dtype: int64

In [29]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,S,3,1,1,Unknown,Southampton,0,False
1,1,1,1,38.0,1,0,71.2833,C,1,0,0,C,Cherbourg,1,False
2,1,3,1,26.0,0,0,7.9250,S,3,0,0,Unknown,Southampton,1,True
3,1,1,1,35.0,1,0,53.1000,S,1,0,0,C,Southampton,1,False
4,0,3,0,35.0,0,0,8.0500,S,3,1,1,Unknown,Southampton,0,True

In [30]:
df['embark_town'].value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [31]:
X = df[['age','fare','sex','pclass']]
y = df['survived']

In [34]:
#Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, 
                                               test_size=0.20,
                                               random_state=42)

In [38]:
# Logistic Regression model & Metrics 
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
from sklearn.metrics import accuracy_score,mean_squared_error 
mse=mean_squared_error(y_test,y_pred)
acc_score=accuracy_score(y_test,y_pred)
from sklearn.metrics import confusion_matrix
con_mat=confusion_matrix(y_test,y_pred)
from sklearn.metrics import classification_report
class_rep=classification_report(y_test,y_pred)
print("Accuracy score:", acc_score)
print("Confusion matrix:",con_mat)
print("Classification Report:",class_rep,)

Accuracy score: 0.7921348314606742
Confusion matrix: [[87 22]
 [15 54]]
Classification Report:               precision    recall  f1-score   support

           0       0.85      0.80      0.82       109
           1       0.71      0.78      0.74        69

    accuracy                           0.79       178
   macro avg       0.78      0.79      0.78       178
weighted avg       0.80      0.79      0.79       178

In [53]:
#Decision Tree Classifier Alg
from sklearn.tree import DecisionTreeClassifier
model1=DecisionTreeClassifier()
model1.fit(X_train,y_train)
y_pred1=model1.predict(X_test)
acc_score1=accuracy_score(y_test,y_pred1)
print(acc_score1)
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

0.7640449438202247
[[82 27]
 [15 54]]
              precision    recall  f1-score   support

           0       0.85      0.75      0.80       109
           1       0.67      0.78      0.72        69

    accuracy                           0.76       178
   macro avg       0.76      0.77      0.76       178
weighted avg       0.78      0.76      0.77       178

In [55]:
#Random Forest Classifier Alg
from sklearn.ensemble import RandomForestClassifier
model2=RandomForestClassifier()
model2.fit(X_train,y_train)
y_pred2=model2.predict(X_test)
acc_score2=accuracy_score(y_test,y_pred2)
print(acc_score2)
print(confusion_matrix(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

0.8202247191011236
[[90 19]
 [13 56]]
              precision    recall  f1-score   support

           0       0.87      0.83      0.85       109
           1       0.75      0.81      0.78        69

    accuracy                           0.82       178
   macro avg       0.81      0.82      0.81       178
weighted avg       0.82      0.82      0.82       178

In [57]:
# KNN Model
from sklearn.neighbors import KNeighborsClassifier
model4=KNeighborsClassifier()
model4.fit(X_train, y_train)
y_pred4=model.predict(X_test)
acc_score4=accuracy_score(y_test,y_pred4)
print("Accuracy Score:", acc_score4)
print(confusion_matrix(y_test,y_pred4))
print(classification_report(y_test,y_pred4))

Accuracy Score: 0.7921348314606742
[[87 22]
 [15 54]]
              precision    recall  f1-score   support

           0       0.85      0.80      0.82       109
           1       0.71      0.78      0.74        69

    accuracy                           0.79       178
   macro avg       0.78      0.79      0.78       178
weighted avg       0.80      0.79      0.79       178

In [58]:
from sklearn.svm import SVC
model5=SVC()
model5.fit(X_train,y_train)
y_pred5=model5.predict(X_test)
acc_score5=accuracy_score(y_test,y_pred5)
print("Accuracy Score:", acc_score5)
print(confusion_matrix(y_test,y_pred5))
print(classification_report(y_test,y_pred5))

Accuracy Score: 0.6797752808988764
[[100   9]
 [ 48  21]]
              precision    recall  f1-score   support

           0       0.68      0.92      0.78       109
           1       0.70      0.30      0.42        69

    accuracy                           0.68       178
   macro avg       0.69      0.61      0.60       178
weighted avg       0.69      0.68      0.64       178

In [61]:
## COMPARISON OF ALL TESTS WITH ACCURACY CON_MATRIX,CLASSIFICATION REPORT
accuracy_scores={
    'LogisticRegression' :accuracy_score(y_test,y_pred),
    'DecisionTree' :  accuracy_score(y_test,y_pred1),
    'RandomForest' : accuracy_score(y_test,y_pred2),
    'KNNModel' : accuracy_score(y_test,y_pred4),
    'SVCModel': accuracy_score(y_test,y_pred5),
}
accuracy_scores

{'LogisticRegression': 0.7921348314606742,
 'DecisionTree': 0.7640449438202247,
 'RandomForest': 0.8202247191011236,
 'KNNModel': 0.7921348314606742,
 'SVCModel': 0.6797752808988764}

In [64]:
max(accuracy_scores, key=accuracy_scores.get)

'RandomForest'

In [85]:
print("LogisticREgression:",confusion_matrix(y_test, y_pred),classification_report(y_test, y_pred))
print("DecisionTree:",confusion_matrix(y_test, y_pred1),classification_report(y_test, y_pred1))   
print("RandomForest:",confusion_matrix(y_test, y_pred2),classification_report(y_test, y_pred2))
print("KNNModel:",confusion_matrix(y_test, y_pred4), classification_report(y_test, y_pred4))
print("SVCModel:", confusion_matrix(y_test, y_pred5),classification_report(y_test, y_pred5))

LogisticREgression: [[87 22]
 [15 54]]               precision    recall  f1-score   support

           0       0.85      0.80      0.82       109
           1       0.71      0.78      0.74        69

    accuracy                           0.79       178
   macro avg       0.78      0.79      0.78       178
weighted avg       0.80      0.79      0.79       178

DecisionTree: [[82 27]
 [15 54]]               precision    recall  f1-score   support

           0       0.85      0.75      0.80       109
           1       0.67      0.78      0.72        69

    accuracy                           0.76       178
   macro avg       0.76      0.77      0.76       178
weighted avg       0.78      0.76      0.77       178

RandomForest: [[90 19]
 [13 56]]               precision    recall  f1-score   support

           0       0.87      0.83      0.85       109
           1       0.75      0.81      0.78        69

    accuracy                           0.82       178
   macro avg       0.81      0.82      0.81       178
weighted avg       0.82      0.82      0.82       178

KNNModel: [[87 22]
 [15 54]]               precision    recall  f1-score   support

           0       0.85      0.80      0.82       109
           1       0.71      0.78      0.74        69

    accuracy                           0.79       178
   macro avg       0.78      0.79      0.78       178
weighted avg       0.80      0.79      0.79       178

SVCModel: [[100   9]
 [ 48  21]]               precision    recall  f1-score   support

           0       0.68      0.92      0.78       109
           1       0.70      0.30      0.42        69

    accuracy                           0.68       178
   macro avg       0.69      0.61      0.60       178
weighted avg       0.69      0.68      0.64       178