In [4]:
data=([[24,170,84,100],[28,168,80,120],[32,171,75,105],[34,170,78,108],
               [36,164,80,100]])
data

[[24, 170, 84, 100],
 [28, 168, 80, 120],
 [32, 171, 75, 105],
 [34, 170, 78, 108],
 [36, 164, 80, 100]]

In [6]:
import pandas as pd
df=pd.DataFrame(data)
df

    0    1   2    3
0  24  170  84  100
1  28  168  80  120
2  32  171  75  105
3  34  170  78  108
4  36  164  80  100

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.columns=['age','height','weight','bp']
df

   age  height  weight   bp
0   24     170      84  100
1   28     168      80  120
2   32     171      75  105
3   34     170      78  108
4   36     164      80  100

In [9]:
df.index=['a','b','c','d','e']

In [12]:
df

   age  height  weight   bp
a   24     170      84  100
b   28     168      80  120
c   32     171      75  105
d   34     170      78  108
e   36     164      80  100

In [10]:
print("mean: ", df["age"].mean())
print("median: ", df["bp"].median())
print("mode:", df["height"].mode())
print("standard deviation: ", df["weight"].std())
print("variance: ",df["bp"].var())

mean:  30.8
median:  105.0
mode: 0    170
Name: height, dtype: int64
standard deviation:  3.2863353450309964
variance:  67.8

In [11]:
df["weight"].describe()

count     5.000000
mean     79.400000
std       3.286335
min      75.000000
25%      78.000000
50%      80.000000
75%      80.000000
max      84.000000
Name: weight, dtype: float64

In [20]:
df["height"].mode()

0    170
Name: height, dtype: int64

In [22]:
df["height"].describe()

count      5.000000
mean     168.600000
std        2.792848
min      164.000000
25%      168.000000
50%      170.000000
75%      170.000000
max      171.000000
Name: height, dtype: float64