In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('D:\csv files\Diab.csv')
df.head()
df.info()
df_cat=df[['Gender','Diabetic']]
print(df_cat)
df_cont=df.iloc[ : ,2:6]
print(df_cont)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pat_Id    500 non-null    int64
 1   Gender    500 non-null    object
 2   OGTT      500 non-null    int64
 3   DBP       500 non-null    int64
 4   BMI       500 non-null    float64
 5   Age       500 non-null    int64
 6   Diabetic  500 non-null    object
dtypes: float64(1), int64(4), object(2)
memory usage: 27.5+ KB
     Gender Diabetic
0      Male      Yes
1      Male       No
2      Male       No
3    Female      Yes
4    Female       No
..      ...      ...
495    Male       No
496  Female       No
497  Female       No
498  Female       No
499    Male       No

[500 rows x 2 columns]
     OGTT  DBP   BMI  Age
0     176   90  33.7   58
1     150   66  34.7   42
2      73   50  23.0   21
3     187   68  37.7   41
4     100   88  46.8   31
..    ...  ...   ...  ...
495   130   96  22.6   21
496   111   58  29.5   22
497    98   60  34.7   22
498   143   86  30.1   23
499   121   78  27.8   38

[500 rows x 4 columns]

In [2]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss_x=ss.fit_transform(df_cont)
ss_x=pd.DataFrame(ss_x)
ss_x.columns=["OGTT","DBP","BMI","Age"]
ss_x.head()

       OGTT       DBP       BMI       Age
0  1.806312  1.512904  0.191222  2.133749
1  0.957604 -0.537564  0.334117  0.769678
2 -1.555878 -1.904543 -1.337752 -1.020667
3  2.165380 -0.366692  0.762801  0.684423
4 -0.674527  1.342031  2.063143 -0.168122

In [3]:
from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler()
mm_x=mm.fit_transform(df_cont)
mm_x=pd.DataFrame(mm_x)
mm_x.columns=["OGTT","DBP", "BMI","Age"]
mm_x.head()

       OGTT       DBP       BMI       Age
0  0.857143  0.652174  0.316973  0.616667
1  0.688312  0.391304  0.337423  0.350000
2  0.188312  0.217391  0.098160  0.000000
3  0.928571  0.413043  0.398773  0.333333
4  0.363636  0.630435  0.584867  0.166667

In [4]:
#Label Encoder for transfer text to numeric
from sklearn.preprocessing import LabelEncoder
df_cat=df[["Gender","Diabetic"]].copy()
LE=LabelEncoder()
df_cat["Gender_LE"]=LE.fit_transform(df_cat["Gender"])
df_cat["Diabetic_LE"]=LE.fit_transform(df_cat["Diabetic"])
df_cat.head()

   Gender Diabetic  Gender_LE  Diabetic_LE
0    Male      Yes          1            1
1    Male       No          1            0
2    Male       No          1            0
3  Female      Yes          0            1
4  Female       No          0            0

In [5]:
from sklearn.preprocessing import OneHotEncoder
OHE=OneHotEncoder()
df_G=pd.DataFrame(OHE.fit_transform(df_cat[["Gender"]]).toarray())
df_G.columns=['Female','Male']
print(df_G)

     Female  Male
0       0.0   1.0
1       0.0   1.0
2       0.0   1.0
3       1.0   0.0
4       1.0   0.0
..      ...   ...
495     0.0   1.0
496     1.0   0.0
497     1.0   0.0
498     1.0   0.0
499     0.0   1.0

[500 rows x 2 columns]

In [6]:
df_d=pd.DataFrame(OHE.fit_transform(df_cat[["Diabetic"]]).toarray())
df_d.columns=['No','yes']
print(df_d)

      No  yes
0    0.0  1.0
1    1.0  0.0
2    1.0  0.0
3    0.0  1.0
4    1.0  0.0
..   ...  ...
495  1.0  0.0
496  1.0  0.0
497  1.0  0.0
498  1.0  0.0
499  1.0  0.0

[500 rows x 2 columns]

In [7]:
#Ordinal Encoder
from sklearn.preprocessing import OrdinalEncoder
df=pd.read_csv("D:\csv files\Diab.csv")
cat_cols=["Gender","Diabetic"]
oe=OrdinalEncoder()
df[cat_cols]=oe.fit_transform(df[cat_cols])
print(df.head())

   Pat_Id  Gender  OGTT  DBP   BMI  Age  Diabetic
0     101     1.0   176   90  33.7   58       1.0
1     102     1.0   150   66  34.7   42       0.0
2     103     1.0    73   50  23.0   21       0.0
3     104     0.0   187   68  37.7   41       1.0
4     105     0.0   100   88  46.8   31       0.0

In [8]:
#Holdout methods
import numpy as np
import pandas as pd
df=pd.read_csv('D:\csv files\Advertising.csv')
df.head()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,27-03-2016 00:53,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,04-04-2016 01:39,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,13-03-2016 20:35,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,10-01-2016 02:31,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,03-06-2016 03:36,0

In [9]:
df.columns

Index(['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage', 'Ad Topic Line', 'City', 'Male', 'Country',
       'Timestamp', 'Clicked on Ad'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   object
 5   City                      1000 non-null   object
 6   Male                      1000 non-null   int64
 7   Country                   1000 non-null   object
 8   Timestamp                 1000 non-null   object
 9   Clicked on Ad             1000 non-null   int64
dtypes: float64(3), int64(3), object(4)
memory usage: 78.3+ KB

In [11]:
#Holdout Method
from sklearn.model_selection import train_test_split
x=df[['Daily Time Spent on Site', 'Age','Area Income', 
      'Daily Internet Usage', 'Male']]
y=df['Clicked on Ad']
x_train, x_test, y_train, y_test= train_test_split(x,y,
                                          test_size=0.3, 
                                          random_state=42,
                                          stratify=y
                                         )
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((700, 5), (300, 5), (700,), (300,))

In [12]:
#stratified sampling cross validation
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
log_reg=LogisticRegression(max_iter=1000)
log_reg.fit(x_train,y_train)
y_train_pred=log_reg.predict(x_train)
y_test_pred=log_reg.predict(x_test)
train_accuracy=accuracy_score(y_train,y_train_pred)
test_accuracy=accuracy_score(y_test,y_test_pred)
print(f"training Accuracy:{train_accuracy}")
print(f"testing Accuracy:{test_accuracy}")

training Accuracy:0.9685714285714285
testing Accuracy:0.9766666666666667

In [13]:
#Shuffle split Cross Validation using LR
import pandas as pd 
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import ShuffleSplit, cross_validate
model=LogisticRegression(solver='liblinear')
shuffle_split=ShuffleSplit(n_splits=200,
                           test_size=0.3,
                           random_state=42,
                          )
cv_results=cross_validate(model,x,y,
                           cv=shuffle_split,
                           scoring='accuracy',
                           return_train_score=True
                          )
train_scores=cv_results['train_score']
test_scores=cv_results['test_score']
print("cross validation train Accuracy:",np.round(train_scores.mean(),2))
print("corss validation test Accuracy:",np.round(test_scores.mean(),2))

cross validation train Accuracy: 0.9
corss validation test Accuracy: 0.9

In [14]:
#KFOLD cross validation using Logistic Regresssion
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold, cross_validate
kfold=KFold(n_splits=5,
            shuffle=True,
            random_state=42
           )
cv_results=cross_validate(model,x,y,
                          cv=kfold,
                          scoring='accuracy',
                          return_train_score=True
                         )
train_scores=cv_results['train_score']
test_scores=cv_results['test_score']
print("cross validation: train Accuracy:",np.round(train_scores.mean(),2))
print("corss validation: test Accuracy:",np.round(test_scores.mean(),2))

cross validation: train Accuracy: 0.9
corss validation: test Accuracy: 0.9