In [1]:
import pandas as pd
df=pd.read_csv("D:\csv files\experience_vs_salary.csv")

In [2]:
df

   Experience (Years)  Salary ($)
0                   1       30000
1                   2       35000
2                   3       40000
3                   4       45000
4                   5       50000
5                   6       60000
6                   7       65000
7                   8       75000
8                   9       85000
9                  10       95000

In [3]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
x=df[["Experience (Years)"]]
y=df[["Salary ($)"]]
print(x)
print(y)

   Experience (Years)
0                   1
1                   2
2                   3
3                   4
4                   5
5                   6
6                   7
7                   8
8                   9
9                  10
   Salary ($)
0       30000
1       35000
2       40000
3       45000
4       50000
5       60000
6       65000
7       75000
8       85000
9       95000

In [4]:
model= LinearRegression()
z=model.fit(x,y)
y_pred=model.predict(x)
y_pred

array([[25818.18181818],
       [32969.6969697 ],
       [40121.21212121],
       [47272.72727273],
       [54424.24242424],
       [61575.75757576],
       [68727.27272727],
       [75878.78787879],
       [83030.3030303 ],
       [90181.81818182]])

In [8]:
r2=r2_score(y,y_pred)
mse=mean_squared_error(y,y_pred)
mse

9060606.060606051

In [6]:
r2

0.9789777121563664

In [9]:
import pandas as pd
import numpy as np
df=pd.read_csv("D:\csv files\Cars_4vars.csv")

In [10]:
df.head()

   HP        MPG  VOL          SP         WT
0  49  53.700681   89  104.185353  28.762059
1  55  50.013401   92  105.461264  30.466833
2  55  50.013401   92  105.461264  30.193597
3  70  45.696322   92  113.461264  30.632114
4  53  50.504232   92  104.461264  29.889149

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   HP      81 non-null     int64
 1   MPG     81 non-null     float64
 2   VOL     81 non-null     int64
 3   SP      81 non-null     float64
 4   WT      81 non-null     float64
dtypes: float64(3), int64(2)
memory usage: 3.3 KB

In [12]:
df.corr()

           HP       MPG       VOL        SP        WT
HP   1.000000 -0.725038  0.077459  0.973848  0.076513
MPG -0.725038  1.000000 -0.529057 -0.687125 -0.526759
VOL  0.077459 -0.529057  1.000000  0.102170  0.999203
SP   0.973848 -0.687125  0.102170  1.000000  0.102439
WT   0.076513 -0.526759  0.999203  0.102439  1.000000

In [13]:
x_sp=df[['SP']]
y_hp=df['HP']
model_hp_sp=LinearRegression()
model_hp_sp.fit(x_sp,y_hp)
y_hp_pred=model_hp_sp.predict(x_sp)
r2_hp_sp=r2_score(y_hp,y_hp_pred)
vif_hp_sp=1/(1-r2_hp_sp)
print("R square",r2_hp_sp)
print("VIF: ", vif_hp_sp)

R square 0.9483800677016775
VIF:  19.372361711379014

In [14]:
#volume vs weight
x_vol=df[['VOL']]
y_wt=df['WT']
model_wt_vol=LinearRegression()
model_wt_vol.fit(x_vol,y_wt)
y_wt_pred=model_wt_vol.predict(x_vol)
r2_wt_vol=r2_score(y_wt,y_wt_pred)
vif_wt_vol=1/(1-r2_wt_vol)
print("R square",r2_wt_vol)
print("VIF: ", vif_wt_vol)

R square 0.9984067954549005
VIF:  627.6657966335137

In [15]:
#VOLUME vs HP
x_vol=df[['VOL']]
y_hp=df['HP']
model_hp_vol=LinearRegression()
model_hp_vol.fit(x_vol,y_hp)
y_hp_pred=model_hp_vol.predict(x_vol)
r2_hp_vol=r2_score(y_wt,y_hp_pred)
vif_hp_vol=1/(1-r2_hp_vol)
print("R square",r2_hp_vol)
print("VIF: ", vif_hp_vol)

R square -129.64175265504238
VIF:  0.007654520700135471

In [16]:
#MODEL-1
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
y_multi=df['MPG']
x_model1=df[['HP']]
model1=LinearRegression()
model1.fit(x_model1,y_multi)
y_pred1=model1.predict(x_model1)
r2_model1=r2_score(y_multi,y_pred1)
rmse_model1=np.sqrt(mean_squared_error(y_multi,y_pred1))
print("R²:", r2_model1)
print("RMSE:", rmse_model1)

R²: 0.5256806086282022
RMSE: 6.249962606576023

In [17]:
#MODEL-2
y_multi=df['MPG']
x_model2=df[['HP','SP']]
model2=LinearRegression()
model2.fit(x_model2,y_multi)
y_pred2=model2.predict(x_model2)
r2_model2=r2_score(y_multi,y_pred2)
rmse_model2=np.sqrt(mean_squared_error(y_multi,y_pred2))
print("R²:", r2_model2)
print("RMSE:", rmse_model2)

R²: 0.532639171285165
RMSE: 6.203947782760669

In [18]:
#Model-3
y_multi=df['MPG']
x_model3=df[['HP','SP','VOL']]
model3=LinearRegression()
model3.fit(x_model3,y_multi)
y_pred3=model3.predict(x_model3)
r2_model3=r2_score(y_multi,y_pred3)
rmse_model3=np.sqrt(mean_squared_error(y_multi,y_pred3))
print("R²:", r2_model3)
print("RMSE:", rmse_model3)

R²: 0.770368341321302
RMSE: 4.34868409851891

In [19]:
#Model-4
y_multi=df['MPG']
x_model4=df[['HP','SP','VOL','WT']]
model4=LinearRegression()
model4.fit(x_model4,y_multi)
y_pred4=model4.predict(x_model4)
r2_model4=r2_score(y_multi,y_pred4)
rmse_model4=np.sqrt(mean_squared_error(y_multi,y_pred4))
print("R²:", r2_model4)
print("RMSE:", rmse_model4)

R²: 0.7705372737359844
RMSE: 4.347084212704316

In [20]:
model_results=pd.DataFrame({
    "Model":["HP Only", "HP+SP","HP+SP+VOL","HP+SP+VOL+WT"],
    "R_Squared":[r2_model1,r2_model2,r2_model3,r2_model4],
    "RMSE":[rmse_model1,rmse_model2,rmse_model3,rmse_model4],
})
print(model_results)

          Model  R_Squared      RMSE
0       HP Only   0.525681  6.249963
1         HP+SP   0.532639  6.203948
2     HP+SP+VOL   0.770368  4.348684
3  HP+SP+VOL+WT   0.770537  4.347084

In [21]:
x_sp=df[["SP"]]
y_hp=df['HP']
model_hp_sp=LinearRegression()
model_hp_sp.fit(x_sp,y_hp)
y_hp_pred=model_hp_sp.predict(x_sp)
r2_hp_sp=r2_score(y_hp,y_hp_pred)
vif_hp_sp=1/(1-r2_hp_sp)
print("R²:", r2_hp_sp)
print("VIF:", vif_hp_sp)

R²: 0.9483800677016775
VIF: 19.372361711379014

In [22]:
x_vol=df[["VOL"]]
y_wt=df['WT']
model_hp_sp=LinearRegression()
model_hp_sp.fit(x_vol,y_wt)
y_wt_pred=model_hp_sp.predict(x_vol)
r2_vol_wt=r2_score(y_wt,y_wt_pred)
vif_vol_wt=1/(1-r2_vol_wt)
print("R²:", r2_vol_wt)
print("VIF:", vif_vol_wt)

R²: 0.9984067954549005
VIF: 627.6657966335137

In [23]:
x_vol=df[["VOL"]]
y_hp=df['HP']
model_hp_sp=LinearRegression()
model_hp_sp.fit(x_vol,y_hp)
y_hp_pred=model_hp_sp.predict(x_vol)
r2_vol_hp=r2_score(y_hp,y_hp_pred)
vif_vol_hp=1/(1-r2_vol_hp)
print("R²:", r2_vol_hp)
print("VIF:", vif_vol_hp)

R²: 0.005999970050444947
VIF: 1.0060361869916135

In [24]:
df.head()

   HP        MPG  VOL          SP         WT
0  49  53.700681   89  104.185353  28.762059
1  55  50.013401   92  105.461264  30.466833
2  55  50.013401   92  105.461264  30.193597
3  70  45.696322   92  113.461264  30.632114
4  53  50.504232   92  104.461264  29.889149

In [25]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
x_best=[['HP','VOL']]
model5=LinearRegression()
model5.fit(x_best,y_multi)
y_pred5=model5.predict(x_best)
r2_model5=r2_score(y_multi,y_pred5)
rmse_model2=np.sqrt(mean_squared_error(y_multi,y_pred2))
import matplotlib.pyplot as plt
import seaborn as sns
residual=y_multi-y_pred5
sns.scatterplot(x=y_pred5,y=residual,alpha=0.7)
plt.axhline(y=0,color='red', linestyle='--')
plt.xlabel('Predicted MPG')
plt.ylabel('Residuals')
plt.title('Residual plot for Homoscedasticity check')
plt.show()

ValueError: dtype='numeric' is not compatible with arrays of bytes/strings.Convert your data to numeric values explicitly instead.